resolver: lts-8.0
packages:
  - '.'
flags:
  snap-extras:
    "Examples": true
extra-deps:
  - digestive-functors-0.8.2.0
  - digestive-functors-heist-0.8.7.0
  - digestive-functors-snap-0.7.0.0
  - heist-1.0.1.0
  - map-syntax-0.2.0.2
  - snap-1.0.0.1
